## YAML Template.
---

spring:
  application:
    name: Inscriptionuniversitaire

server:
  port: 7777

spring.datasource:
        url: jdbc:mysql://localhost:3306/universite
        username: root
        password: 
        driver-class-name: com.mysql.jdbc.Driver
        
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://192.168.8.5:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: localhost
   


