## YAML Template.
---

spring:
  application:
    name: wsFoyer

server: 
  port: 4444

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://192.168.8.5:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: localhost
   
   
    
    
    
    