## YAML Template.
---

spring:
  application:
    name: wsBus

server: 
  port: 3333

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://192.168.8.5:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: localhost
   
    